# Generated by Django 3.2.5 on 2021-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='category',
            field=models.CharField(default='NaN', max_length=50),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='name',
            field=models.CharField(default='NaN', max_length=255),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='price',
            field=models.IntegerField(default='NaN'),
        ),
    ]
