# Generated by Django 3.2.5 on 2021-07-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_alter_outfit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField()),
                ('tag', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('stock', models.IntegerField(default=1)),
                ('image1', models.ImageField(default=None, upload_to='photos/clothes/')),
                ('image2', models.ImageField(default=None, upload_to='photos/clothes/')),
                ('image3', models.ImageField(default=None, upload_to='photos/clothes/')),
                ('image4', models.ImageField(default=None, upload_to='photos/clothes/')),
                ('image5', models.ImageField(default=None, upload_to='photos/clothes/')),
                ('slug', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Clothe',
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
